d /var/lib/game-control 0700 root root -
d /var/lib/game-control/log-checkpoints 0700 root root -
d /etc/game-control/jvm 0700 root root -
d /var/lib/game-control-web 0700 gamecontrol gamecontrol -
d /run/game-control 0755 root root -
d /run/game-slot 0770 root gameslot -
d /opt/game-servers/minecraft-sunlit-cobblemon 0755 root root -
d /opt/game-servers/minecraft-sunlit-cobblemon/releases 0755 root root -
d /srv/game-servers/minecraft-sunlit-cobblemon 0750 svc-sunlit svc-sunlit -
L /srv/game-servers/minecraft-sunlit-cobblemon/libraries - - - - /opt/game-servers/minecraft-sunlit-cobblemon/libraries
d /var/backups/game-servers/minecraft-sunlit-cobblemon 0700 root root -
f /run/game-control/operation.lock 0660 root gameslot -
f /run/game-control/slot.lock 0660 root gameslot -
f /run/game-control/reservation.json 0644 root root -
f /run/game-slot/slot.json 0660 root gameslot -
