window.HORIZON_COMMANDS = {
  "minecraft": [
    { cmd: "list", args: "", help: "Show online players" },
    { cmd: "say", args: "<message>", help: "Broadcast a message" },
    { cmd: "whitelist", args: "add|remove <player>", help: "Manage whitelist" },
    { cmd: "op", args: "<player>", help: "Grant operator" },
    { cmd: "kick", args: "<player> [reason]", help: "Kick a player" },
    { cmd: "save-all", args: "", help: "Flush world to disk" },
    { cmd: "time", args: "set day|night", help: "Set world time" },
    { cmd: "weather", args: "clear|rain|thunder", help: "Set weather" },
    { cmd: "gamemode", args: "<mode> <player>", help: "Change gamemode" },
    { cmd: "tp", args: "<player> <target>", help: "Teleport" },
  ],
  "terraria-vanilla": [
    { cmd: "playing", args: "", help: "List connected players" },
    { cmd: "say", args: "<message>", help: "Broadcast a message" },
    { cmd: "save", args: "", help: "Save the world" },
    { cmd: "time", args: "", help: "Show game time" },
    { cmd: "dawn", args: "", help: "Set time to dawn" },
    { cmd: "noon", args: "", help: "Set time to noon" },
    { cmd: "dusk", args: "", help: "Set time to dusk" },
    { cmd: "midnight", args: "", help: "Set time to midnight" },
    { cmd: "settle", args: "", help: "Settle liquids" },
    { cmd: "kick", args: "<player>", help: "Kick a player" },
    { cmd: "ban", args: "<player>", help: "Ban a player" },
    { cmd: "password", args: "[pass]", help: "Show/set server password" },
    { cmd: "version", args: "", help: "Show server version" },
    { cmd: "help", args: "", help: "List server commands" },
  ],
  "terraria-tmod": "terraria-vanilla",
  "pz-rising": [
    { cmd: "players", args: "", help: "List connected players" },
    { cmd: "servermsg", args: "\"<message>\"", help: "Broadcast a message" },
    { cmd: "save", args: "", help: "Save world state" },
    { cmd: "kickuser", args: "<user>", help: "Kick a player" },
    { cmd: "banuser", args: "<user>", help: "Ban a player" },
    { cmd: "showoptions", args: "", help: "Show server options" },
    { cmd: "checkModsNeedUpdate", args: "", help: "Check workshop mod updates" },
    { cmd: "quit", args: "", help: "Save and shut down (prefer the Stop button)" },
  ],
};
